// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfitFoot.Infrastructure;

#nullable disable

namespace ProfitFood.DAL.Migrations
{
    [DbContext(typeof(ProfitFoodDbContext))]
    partial class ProfitFoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ProfitFood.Domain.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultStorageLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Form299Title")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionShortName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultStorageLocationId");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId", "ChangedAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.DatabaseSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoMigrateOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreateBackupBeforeMigration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabaseFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastBackupAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseSettings", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Documents.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.HasIndex("StorageLocationId", "ProductId")
                        .IsUnique();

                    b.ToTable("StockBalances", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Documents.StockDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedMenuRequirementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMenuRequirementId");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("DocumentNumber", "DocumentDate", "StorageLocationId")
                        .IsUnique();

                    b.ToTable("StockDocuments", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Documents.StockDocumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StockDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockDocumentId");

                    b.HasIndex("UnitId");

                    b.ToTable("StockDocumentItems", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.CycleMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgeGroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgeGroupId");

                    b.HasIndex("SeasonId", "AgeGroupId", "Name");

                    b.ToTable("CycleMenus", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.CycleMenuDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CycleMenuId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CycleMenuId", "DayNumber")
                        .IsUnique();

                    b.ToTable("CycleMenuDays", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.CycleMenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CycleMenuDayId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DishId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeCardVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("RecipeCardVersionId");

                    b.HasIndex("CycleMenuDayId", "MealTypeId", "SortOrder");

                    b.ToTable("CycleMenuItems", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.DailyMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CycleMenuId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MenuDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CycleMenuId");

                    b.HasIndex("MenuDate")
                        .IsUnique();

                    b.HasIndex("SeasonId");

                    b.ToTable("DailyMenus", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.DailyMenuAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActualCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ChildGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DailyMenuId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildGroupId");

                    b.HasIndex("DailyMenuId", "ChildGroupId")
                        .IsUnique();

                    b.ToTable("DailyMenuAttendances", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.DailyMenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DailyMenuId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DishId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeCardVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("RecipeCardVersionId");

                    b.HasIndex("DailyMenuId", "MealTypeId", "SortOrder");

                    b.ToTable("DailyMenuItems", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.MenuRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DailyMenuId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HeadSignerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MedWorkerSignerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrintedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RequirementDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StorekeeperSignerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalChildrenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DailyMenuId")
                        .IsUnique();

                    b.HasIndex("HeadSignerId");

                    b.HasIndex("MedWorkerSignerId");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("StorekeeperSignerId");

                    b.HasIndex("Number", "RequirementDate")
                        .IsUnique();

                    b.ToTable("MenuRequirements", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.MenuRequirementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MenuRequirementId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.HasIndex("MenuRequirementId", "SortOrder");

                    b.ToTable("MenuRequirementItems", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Recipes.RecipeCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DishId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("DishId");

                    b.ToTable("RecipeCards", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Recipes.RecipeCardVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OutputQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutputUnitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeCardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OutputUnitId");

                    b.HasIndex("RecipeCardId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RecipeCardVersions", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LossPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeCardVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.HasIndex("RecipeCardVersionId", "SortOrder");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.AgeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgeFromMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgeToMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AgeGroups", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.ChildGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgeGroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedChildrenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgeGroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ChildGroups", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DishCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DishCategoryId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("Name");

                    b.ToTable("Dishes", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.DishCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DishCategories", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.DishOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgeGroupId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutputQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeCardVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgeGroupId");

                    b.HasIndex("UnitId");

                    b.HasIndex("RecipeCardVersionId", "AgeGroupId")
                        .IsUnique();

                    b.ToTable("DishOutputs", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.MealType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MealTypes", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Article")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BaseUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPerishable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinStock")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StorageUnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("Name");

                    b.HasIndex("StorageUnitId");

                    b.HasIndex("ProductCategoryId", "Name");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Seasons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Seasons_MonthFrom", "MonthFrom >= 1 AND MonthFrom <= 12");

                            t.HasCheckConstraint("CK_Seasons_MonthTo", "MonthTo >= 1 AND MonthTo <= 12");
                        });
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("StorageLocations", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Signer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullName", "Position");

                    b.ToTable("Signers", (string)null);
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.AppSettings", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.StorageLocation", "DefaultStorageLocation")
                        .WithMany("SettingsAsDefaultStorage")
                        .HasForeignKey("DefaultStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultStorageLocation");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Documents.StockBalance", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.StorageLocation", "StorageLocation")
                        .WithMany("StockBalances")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.Unit", "Unit")
                        .WithMany("StockBalances")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StorageLocation");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Documents.StockDocument", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.Menus.MenuRequirement", "RelatedMenuRequirement")
                        .WithMany("StockDocuments")
                        .HasForeignKey("RelatedMenuRequirementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProfitFood.Domain.Entities.References.StorageLocation", "StorageLocation")
                        .WithMany("StockDocuments")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedMenuRequirement");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Documents.StockDocumentItem", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.Product", "Product")
                        .WithMany("StockDocumentItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.Documents.StockDocument", "StockDocument")
                        .WithMany("Items")
                        .HasForeignKey("StockDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.Unit", "Unit")
                        .WithMany("StockDocumentItems")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockDocument");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.CycleMenu", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.AgeGroup", "AgeGroup")
                        .WithMany("CycleMenus")
                        .HasForeignKey("AgeGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProfitFood.Domain.Entities.References.Season", "Season")
                        .WithMany("CycleMenus")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AgeGroup");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.CycleMenuDay", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.Menus.CycleMenu", "CycleMenu")
                        .WithMany("Days")
                        .HasForeignKey("CycleMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CycleMenu");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.CycleMenuItem", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.Menus.CycleMenuDay", "CycleMenuDay")
                        .WithMany("Items")
                        .HasForeignKey("CycleMenuDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.Dish", "Dish")
                        .WithMany("CycleMenuItems")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.MealType", "MealType")
                        .WithMany("CycleMenuItems")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.Recipes.RecipeCardVersion", "RecipeCardVersion")
                        .WithMany("CycleMenuItems")
                        .HasForeignKey("RecipeCardVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CycleMenuDay");

                    b.Navigation("Dish");

                    b.Navigation("MealType");

                    b.Navigation("RecipeCardVersion");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.DailyMenu", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.Menus.CycleMenu", "CycleMenu")
                        .WithMany("DailyMenus")
                        .HasForeignKey("CycleMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProfitFood.Domain.Entities.References.Season", "Season")
                        .WithMany("DailyMenus")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CycleMenu");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.DailyMenuAttendance", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.ChildGroup", "ChildGroup")
                        .WithMany("DailyMenuAttendances")
                        .HasForeignKey("ChildGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.Menus.DailyMenu", "DailyMenu")
                        .WithMany("Attendances")
                        .HasForeignKey("DailyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildGroup");

                    b.Navigation("DailyMenu");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.DailyMenuItem", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.Menus.DailyMenu", "DailyMenu")
                        .WithMany("Items")
                        .HasForeignKey("DailyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.Dish", "Dish")
                        .WithMany("DailyMenuItems")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.MealType", "MealType")
                        .WithMany("DailyMenuItems")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.Recipes.RecipeCardVersion", "RecipeCardVersion")
                        .WithMany("DailyMenuItems")
                        .HasForeignKey("RecipeCardVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyMenu");

                    b.Navigation("Dish");

                    b.Navigation("MealType");

                    b.Navigation("RecipeCardVersion");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.MenuRequirement", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.Menus.DailyMenu", "DailyMenu")
                        .WithOne("MenuRequirement")
                        .HasForeignKey("ProfitFood.Domain.Entities.Menus.MenuRequirement", "DailyMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.Signer", "HeadSigner")
                        .WithMany("HeadSignedRequirements")
                        .HasForeignKey("HeadSignerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProfitFood.Domain.Entities.Signer", "MedWorkerSigner")
                        .WithMany("MedWorkerSignedRequirements")
                        .HasForeignKey("MedWorkerSignerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProfitFood.Domain.Entities.References.StorageLocation", "StorageLocation")
                        .WithMany("MenuRequirements")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.Signer", "StorekeeperSigner")
                        .WithMany("StorekeeperSignedRequirements")
                        .HasForeignKey("StorekeeperSignerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyMenu");

                    b.Navigation("HeadSigner");

                    b.Navigation("MedWorkerSigner");

                    b.Navigation("StorageLocation");

                    b.Navigation("StorekeeperSigner");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.MenuRequirementItem", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.Menus.MenuRequirement", "MenuRequirement")
                        .WithMany("Items")
                        .HasForeignKey("MenuRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.Product", "Product")
                        .WithMany("MenuRequirementItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.Unit", "Unit")
                        .WithMany("MenuRequirementItems")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuRequirement");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Recipes.RecipeCard", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.Dish", "Dish")
                        .WithMany("RecipeCards")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Recipes.RecipeCardVersion", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.Unit", "OutputUnit")
                        .WithMany("OutputRecipeVersions")
                        .HasForeignKey("OutputUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.Recipes.RecipeCard", "RecipeCard")
                        .WithMany("Versions")
                        .HasForeignKey("RecipeCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OutputUnit");

                    b.Navigation("RecipeCard");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.Product", "Product")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.Recipes.RecipeCardVersion", "RecipeCardVersion")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeCardVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.Unit", "Unit")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RecipeCardVersion");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.ChildGroup", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.AgeGroup", "AgeGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("AgeGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgeGroup");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Dish", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.DishCategory", "DishCategory")
                        .WithMany("Dishes")
                        .HasForeignKey("DishCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.MealType", "MealType")
                        .WithMany("Dishes")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DishCategory");

                    b.Navigation("MealType");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.DishOutput", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.AgeGroup", "AgeGroup")
                        .WithMany("DishOutputs")
                        .HasForeignKey("AgeGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.Recipes.RecipeCardVersion", "RecipeCardVersion")
                        .WithMany("DishOutputs")
                        .HasForeignKey("RecipeCardVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.Unit", "Unit")
                        .WithMany("DishOutputs")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgeGroup");

                    b.Navigation("RecipeCardVersion");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Product", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.Unit", "BaseUnit")
                        .WithMany("BaseProducts")
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProfitFood.Domain.Entities.References.Unit", "StorageUnit")
                        .WithMany("StorageProducts")
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");

                    b.Navigation("ProductCategory");

                    b.Navigation("StorageUnit");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.ProductCategory", b =>
                {
                    b.HasOne("ProfitFood.Domain.Entities.References.ProductCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Documents.StockDocument", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.CycleMenu", b =>
                {
                    b.Navigation("DailyMenus");

                    b.Navigation("Days");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.CycleMenuDay", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.DailyMenu", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Items");

                    b.Navigation("MenuRequirement");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Menus.MenuRequirement", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StockDocuments");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Recipes.RecipeCard", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Recipes.RecipeCardVersion", b =>
                {
                    b.Navigation("CycleMenuItems");

                    b.Navigation("DailyMenuItems");

                    b.Navigation("DishOutputs");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.AgeGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("CycleMenus");

                    b.Navigation("DishOutputs");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.ChildGroup", b =>
                {
                    b.Navigation("DailyMenuAttendances");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Dish", b =>
                {
                    b.Navigation("CycleMenuItems");

                    b.Navigation("DailyMenuItems");

                    b.Navigation("RecipeCards");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.DishCategory", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.MealType", b =>
                {
                    b.Navigation("CycleMenuItems");

                    b.Navigation("DailyMenuItems");

                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Product", b =>
                {
                    b.Navigation("MenuRequirementItems");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("StockBalances");

                    b.Navigation("StockDocumentItems");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.ProductCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Season", b =>
                {
                    b.Navigation("CycleMenus");

                    b.Navigation("DailyMenus");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.StorageLocation", b =>
                {
                    b.Navigation("MenuRequirements");

                    b.Navigation("SettingsAsDefaultStorage");

                    b.Navigation("StockBalances");

                    b.Navigation("StockDocuments");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.References.Unit", b =>
                {
                    b.Navigation("BaseProducts");

                    b.Navigation("DishOutputs");

                    b.Navigation("MenuRequirementItems");

                    b.Navigation("OutputRecipeVersions");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("StockBalances");

                    b.Navigation("StockDocumentItems");

                    b.Navigation("StorageProducts");
                });

            modelBuilder.Entity("ProfitFood.Domain.Entities.Signer", b =>
                {
                    b.Navigation("HeadSignedRequirements");

                    b.Navigation("MedWorkerSignedRequirements");

                    b.Navigation("StorekeeperSignedRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
